<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fbMotorisedCB" Id="{0694e418-c73d-46ac-9391-384815d288cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbMotorisedCB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
VAR_IN_OUT
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbMotorisedCB">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>