<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{1504ce68-47a1-4b47-8617-25bedc0a150a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[POU_TestBase();

//AlarmWithCustomSourceInfo();
//OtherAlarmsWithCustomSource();
P_AlarmHandling();
P_AlarmTable();
MultipleAlarmCreation();

P_EventLogger_TCSAlarms();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="108" Count="0" />
      <LineId Id="129" Count="0" />
      <LineId Id="107" Count="0" />
      <LineId Id="109" Count="0" />
      <LineId Id="111" Count="0" />
      <LineId Id="119" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="121" Count="0" />
      <LineId Id="120" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>