<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fbIO_AnalogueOutput" Id="{19ccdb33-0c10-46c5-a008-b409d48dd41a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbIO_AnalogueOutput
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbIO_AnalogueOutput">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>