<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fbIO_AnalogueInput" Id="{805e4ee0-1d54-44f1-bb8f-ec68bf186558}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbIO_AnalogueInput
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbIO_AnalogueInput">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>